name: build-jar-plugin

on: [push, workflow_dispatch]
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check version
        run: |
          java -version
          gradle -v

      - name: Cache community build
        uses: actions/cache@v4
        with:
          path: community/build
          key: community-${{ hashFiles('community/**/*.gradle*') }}
          
      - name: Build community
        working-directory: community
        run: |
          if [ ! -f build/distributions/rider-godot-community.zip ]; then
            ./gradlew buildPlugin
          else
            echo "skip community build"
          fi
      
      - name: Build gdscript
        working-directory: gdscript
        run: ./gradlew buildPlugin

      # Store an already-built plugin as an artifact for downloading
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: gdscript-plugin
          path: gdscript/build/distributions/*
